# Generated by Django 6.0.7 on 2026-07-15 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
        ("posts", "0005_alter_post_unique_together"),
        ("votes", "0002_alter_postvote_unique_together_remove_postvote_post_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(choices=[(1, "Апвоут"), (-1, "Даунвоут")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Голос за комментарий",
                "verbose_name_plural": "Голоса за комментарии",
            },
        ),
        migrations.CreateModel(
            name="PostVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(choices=[(1, "Апвоут"), (-1, "Даунвоут")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Голос за пост",
                "verbose_name_plural": "Голоса за посты",
            },
        ),
        migrations.RemoveIndex(
            model_name="vote",
            name="votes_vote_post_id_86e32e_idx",
        ),
        migrations.RemoveIndex(
            model_name="vote",
            name="votes_vote_comment_5b8c3f_idx",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_user_post_vote",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_user_comment_vote",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="vote_either_post_or_comment",
        ),
        migrations.AddField(
            model_name="commentvote",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="comments.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postvote",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentvote",
            unique_together={("user", "comment")},
        ),
        migrations.AlterUniqueTogether(
            name="postvote",
            unique_together={("user", "post")},
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
