# Generated by Django 6.0.7 on 2026-07-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Причина удаления',
                'verbose_name_plural': 'Причины удаления',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('resolved', 'Решена'), ('dismissed', 'Отклонена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.CreateModel(
            name='ModLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('remove_post', 'Удаление поста'), ('remove_comment', 'Удаление комментария'), ('ban_user', 'Бан пользователя'), ('unban_user', 'Разбан'), ('pin_post', 'Закрепление поста'), ('unpin_post', 'Открепление поста'), ('edit_community', 'Изменение сообщества')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_logs', to='communities.community')),
            ],
            options={
                'verbose_name': 'Лог модерации',
                'verbose_name_plural': 'Логи модерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
