# Generated by Django 6.0.7 on 2026-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('community_type', models.CharField(choices=[('public', 'Открытое'), ('restricted', 'Ограниченное'), ('private', 'Закрытое')], default='public', max_length=20, verbose_name='Тип')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='community_avatars/', verbose_name='Аватар')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='community_banners/', verbose_name='Баннер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='Участников')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['-member_count'],
            },
        ),
        migrations.CreateModel(
            name='CommunityBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Бан в сообществе',
                'verbose_name_plural': 'Баны в сообществах',
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Участник сообщества',
                'verbose_name_plural': 'Участники сообществ',
            },
        ),
        migrations.CreateModel(
            name='CommunityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['order'],
            },
        ),
    ]
