# Generated by Django 6.0.7 on 2026-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
