# Generated by Django 6.0.7 on 2026-07-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_community_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="is_active",
        ),
    ]
