# Generated by Django 6.0.7 on 2026-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('post_type', models.CharField(choices=[('text', 'Текст'), ('link', 'Ссылка'), ('image', 'Изображение'), ('video', 'Видео'), ('poll', 'Опрос')], default='text', max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Изображение')),
                ('score', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Комментариев')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплён')),
                ('is_nsfw', models.BooleanField(default=False, verbose_name='NSFW')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='Спойлер')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('harassment', 'Домогательство'), ('hate', 'Разжигание ненависти'), ('nsfw', 'NSFW без метки'), ('misinformation', 'Дезинформация'), ('other', 'Другое')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Жалоба на пост',
                'verbose_name_plural': 'Жалобы на посты',
            },
        ),
        migrations.CreateModel(
            name='PostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сохранённый пост',
                'verbose_name_plural': 'Сохранённые посты',
            },
        ),
    ]
