# Generated by Django 6.0.7 on 2026-07-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_is_active'),
        ('posts', '0003_post_posts_post_score_e8bdff_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_score_e8bdff_idx',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('community', 'slug')},
        ),
    ]
