# Generated by Django 6.1 on 2026-08-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_remove_post_posts_post_score_e8bdff_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together=set(),
        ),
    ]
