# Generated by Django 6.0.7 on 2026-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment_post", "Новый комментарий к посту"),
                    ("reply", "Ответ на комментарий"),
                    ("mention", "Упоминание"),
                    ("upvote_post", "Апвоут поста"),
                    ("upvote_comment", "Апвоут комментария"),
                    ("follow", "Новый подписчик"),
                    ("mod_action", "Модераторское действие"),
                    ("community_invite", "Приглашение в сообщество"),
                ],
                max_length=20,
            ),
        ),
    ]
